### ISSUE TITLE
Evaluate `gpt-3.5-turbo-instruct` as the default model for agents

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#245]
Currently, we use `gpt-4` as the default model that drives ReAct agents. To this day, not all users have access to it. It's also more slow and expensive to use.

We should evaluate the newly announced `gpt-3.5-turbo-instruct` as the default model for agents.

**Comment by collindutter** [comment]
After much investigation, I don't think it's a good default driver with the framework's current abstractions. After some serious prompt tweaking I've gotten it to handle basic tools pretty well, but it's a dice roll on multi-step CoT because it frequently confuses memory and tools. I think part of the problem is that our action schema allows for passing memories actions with "type": "tool" and vice-versa. For instance, this is a perfectly valid action from the LLM's perspective.
```
{
  "type": "tool",
  "name": "TextToolMemory",
  "activity": "summarize",
  "input": {
    "values": {
      "memory_name": "WebSearch",
      "artifact_namespace": "result_2"
    }
  }
}
```
I recommend we can re-evaluate once we reduce Tool Actions and Memory Actions into APIs.
