### ISSUE TITLE
Add Bedrock Cohere Support

### ISSUE THREAD

**Issue by collindutter** [griptape-ai/griptape#312]
The `BedrockPromptDriver` is missing support for Cohere.

**Comment by collindutter** [comment]
@vasinov so this is an interesting one. The Bedrock APIs don't return a token count, and Cohere's tokenizer requires an API key 😕

**Comment by collindutter** [comment]
Related to https://github.com/griptape-ai/griptape/issues/337. Can we skip this parameter entirely?

**Comment by andrewfrench** [comment]
@collindutter according to the [Cohere SDK](https://github.com/cohere-ai/cohere-python/blob/762921dc82b855494d848ebe1df364baa2dfa121/cohere/client.py#L173), it looks like `max_tokens` is an optional API parameter. Would it make sense to send a value if explicitly set by the caller and fall back to the default otherwise?

**Comment by collindutter** [comment]
@andrewfrench I think that's our best option, especially if it's not a required parameter.
