### ISSUE TITLE
Rename `BedrockTitanEmbeddingDriver` to `AmazonBedrockTitanEmbeddingDriver`

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#372]
`BedrockTitanEmbeddingDriver` doesn't follow the naming convention that we use for embedding drivers. It should be renamed to `AmazonBedrockTitanEmbeddingDriver`.

**Comment by KaushikIyer16** [comment]
Hi @vasinov , I also realized that the tokenizer and test files do not have Amazon prepended. Was not sure if I can include all in the same PR. Let me know if I should raise them all in seperate PRs

**Comment by collindutter** [comment]
I think the original reasoning for having the Embedding Driver named `BedrockTitanEmbeddingDriver` was because it was model specific so we went with the the Prompt Model Driver naming convention (`BedrockTitanPromptModelDriver`). Same with the `BedrockTitanTokenizer`.

But agreed, if we're renaming the Embedding Driver we should probably do the same for the Tokenizer. Curious what @vasinov thinks.

**Comment by collindutter** [comment]
@KaushikIyer16 Eventually we may want to refactor Tokenizers and Embedding Drivers to use the the same pattern as Prompt Drivers and Prompt Model Drivers. _If_ we did this we would end up with:
`AmazonBedrockTokenizer`
`BedrockTitanTokenizerModel`
`BedrockClaudeTokenizerModel`
`BedrockJurassicTokenizerModel`

`AmazonBedrockEmbeddingDriver`
`BedrockTitanEmbeddingModelDriver`
...and so on

But today we do not use this pattern and we should name things accordingly. So let's go with:

`AmazonBedrockTitanTokenizer`
`AmazonBedrockClaudeTokenizer`
`AmazonBedrockJurassicTokenizer`

`AmazonBedrockTitanEmbeddingDriver`
