### ISSUE TITLE
OPENAI_API_KEY must be set when exclusively using other models

### ISSUE THREAD

**Issue by gabrielmverreault** [griptape-ai/griptape#471]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
When using `Agent()`, one must define an OpenAI API key even when exclusively using other models.

**To Reproduce**
1. Do NOT specify an OpenAI API Key 
2. Run any of the examples that does not use OpenAI. e.g.: 
```
from griptape.structures import Agent
from griptape.drivers import AmazonBedrockPromptDriver, BedrockJurassicPromptModelDriver

agent = Agent(
    prompt_driver=AmazonBedrockPromptDriver(
        model="ai21.j2-ultra-v1",
        prompt_model_driver=BedrockJurassicPromptModelDriver(top_p=0.95),
        temperature=0.7,
    ),
)
agent.run(
    "Suggest an outline for a blog post based on a title. "
    "Title: How I put the pro in prompt engineering."
)
``` 
It will fail with the following error:
```
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

**Expected behavior**
OpenAI API key only required when using OpenAI models.

**Workaround**
Set an empty OpenAI API key in `.env`
`OPENAI_API_KEY=""`

**Comment by collindutter** [comment]
Hey @gabrielmverreault thank you for the issue! Even though you have overridden the `prompt_driver`, the `embedding_driver` is still defaulting to `OpenAiEmbeddingDriver`. In previous versions this would fail at runtime, but since we [updated](https://github.com/griptape-ai/griptape/commit/1790cfd0074965772aad8f271f919add3da3e8a9) the `openai` SDK it fails at initialization.

You can [override the Embedding Driver](https://docs.griptape.ai/en/latest/griptape-framework/data/embedding-drivers/#override-default-structure-embedding-driver) or disable [Task Memory](https://docs.griptape.ai/en/latest/griptape-framework/tools/task-memory/) by setting `task_memory=None`. 

I am going to keep this issue open since I think we need to update our documentation to better reflect these nuances.

**Comment by collindutter** [comment]
@gabrielmverreault I am going to close this issue as we have made the documentation updates in https://github.com/griptape-ai/griptape-docs/pull/167. But we are going to continue improving the developer experience around defaults on https://github.com/griptape-ai/griptape/issues/242. Stay tuned!
