### ISSUE TITLE
Make preamble in vector query prompt customisable

### ISSUE THREAD

**Issue by igor-2lemetry** [griptape-ai/griptape#641]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
This is a good widely used approach to have a preamble in the very beginning to let LLM to take up a role, before providing the rest of data like user query, contex, etc. It is great to have a default value for it, but many cases and advances users it may matter. So, I believe it is important to make it customisable.

**Describe the solution you'd like**
Provide an ability to overwrite default value by adding new attribute to the TextQueryTask.

**Describe alternatives you've considered**
Alternative is to accept the fate and use the default value.

**Additional context**
No additional context here.

**Comment by collindutter** [comment]
This issue is quite old but for visibility the recommended solution is to pass in a new value for `generate_system_template` into `PromptResponseRagModule`. The [default implementation](https://github.com/griptape-ai/griptape/blob/a9943fb4921014857841ad19490b3f91f92f10bd/griptape/engines/rag/modules/response/prompt_response_rag_module.py#L56-L65) can serve useful resource when creating a new function.
